apiVersion: v1
kind: Service
metadata:
  name: mychart
  labels:
    chart: "mychart-0.1.0"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx
  selector:
    {{- include "mychart.selectorLabels" . | nindent 4 }}
